### ISSUE TITLE
Unexpected behaviour of `make<Presentation<word_type>>

### ISSUE THREAD

**Issue by MTWhyte** [libsemigroups/libsemigroups#417]
When I run the following:
```
LIBSEMIGROUPS_TEST_CASE("fpsemi-examples",
                            "039",
                            "make",
                            "[fpsemi-examples][quick]") {
      std::vector<relation_type> result;
      result.emplace_back<word_type, word_type>({1, 1, 1, 1, 1, 1}, {1, 1, 1, 1});
      auto p = make<Presentation<word_type>>(result);
      REQUIRE(p.rules != p.rules);
    }
```

the output tells me that `p.rules` is:
```
  { { 1, 1, 1, 1, 1, 1 }, { 1, 1, 1, 1 } }
```

I think that it would be better if the output was `{ { 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0 } }`. This would make constructing things like ToddCoxeters from the presentation a bit more seamless, and would be more like what I (I'm not sure about others though) would have expected the presentation to be.

This would be easy to change, it would just be a case of using `presentation::normalize_alphabet` in the definition of `make`. @james-d-mitchell do you think this is a good idea? And would it be better included in #400, or in its own PR?

**Comment by james-d-mitchell** [comment]
I'm surprised that the code you've written even compiles, there shouldn't be a method for `make<Presentation<word_type>>` for vectors. 

Even if this was supposed to be supported, then I'd not suggest doing what you've written, because it violates the [principal of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), to use this we have to remember what transformations are made, when we could just call `normalize_alphabet` knowing that no transformations are made unless explicitly requested.

**Comment by james-d-mitchell** [comment]
I've just tried the code in this issue in the `main` branch and it doesn't compile, so if it compiles for you @MTWhyte it's a result of a change somewhere that's not in the main repo.

**Comment by james-d-mitchell** [comment]
Maybe I wrote too soon, it's possible to use `make` with a vector as an argument, if `fpsemi-examples.hpp` is included, of course! So, I think there's nothing to do to resolve this issue.

**Comment by james-d-mitchell** [comment]
@MTWhyte can we close this issue?

**Comment by MTWhyte** [comment]
Yes, I agree it's less astonishing to not do what I thought!
